#logging:
#  level:
#    ROOT: DEBUG
#    org.springframework.cloud.gateway: DEBUG
server:
  port: 8888
eureka:
  client:
     #下面两项没有代码提示
     serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:1025/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: bulletscreen
        uri: lb://STOMP-WEBSOKET
        predicates:
        - Path=/bullet/info/**
      - id: bulletscreen
        uri: lb:ws://STOMP-WEBSOKET
        predicates:
        - Path=/bullet/**
#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/incaseoffailureusethis
#        - RewritePath=/consumingserviceendpoint, /backingserviceendpoint

      - id: bulletscreen-info1
        uri: lb://STOMP-WEBSOKET
        predicates:
        - Path=/webSocket/info/**
        
      - id: bulletscreen-websocket2
        uri: lb:ws://STOMP-WEBSOKET
        predicates:
        - Path=/webSocket/**
#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/incaseoffailureusethis
#        - RewritePath=/consumingserviceendpoint, /backingserviceendpoint
  endpoints:
    web:
      exposure:
        include: refresh
